"""Compatibility re-exports for lattice model builders."""

from __future__ import annotations

from quantum_lattice_models.hubbard import (
    bose_hubbard_chain,
    bose_hubbard_chain_sparse,
    fermi_hubbard_chain,
    fermi_hubbard_chain_sparse,
)
from quantum_lattice_models.spin import (
    heisenberg_chain,
    heisenberg_ladder,
    j1_j2_heisenberg_chain,
    longitudinal_field_ising,
    next_nearest_neighbor_ising,
    transverse_field_ising,
    xxz_chain,
    xy_chain,
)
from quantum_lattice_models.tight_binding import (
    aubry_andre_harper_chain,
    kagome_lattice_index,
    kagome_lattice_tight_binding,
    kagome_lattice_tight_binding_sparse,
    rice_mele_model,
    square_lattice_index,
    square_lattice_tight_binding,
    square_lattice_tight_binding_sparse,
    ssh_edge_state_localization,
    ssh_edge_state_localizations,
    ssh_model,
    tight_binding_chain,
    tight_binding_chain_sparse,
    triangular_lattice_tight_binding,
    triangular_lattice_tight_binding_sparse,
)
from quantum_lattice_models.topological import (
    haldane_honeycomb_lattice,
    haldane_honeycomb_lattice_sparse,
    harper_hofstadter_square_lattice,
    harper_hofstadter_square_lattice_sparse,
    honeycomb_lattice_index,
    kitaev_chain_bdg,
)

__all__ = [
    "aubry_andre_harper_chain",
    "bose_hubbard_chain",
    "bose_hubbard_chain_sparse",
    "fermi_hubbard_chain",
    "fermi_hubbard_chain_sparse",
    "haldane_honeycomb_lattice",
    "haldane_honeycomb_lattice_sparse",
    "harper_hofstadter_square_lattice",
    "harper_hofstadter_square_lattice_sparse",
    "heisenberg_chain",
    "heisenberg_ladder",
    "honeycomb_lattice_index",
    "j1_j2_heisenberg_chain",
    "kagome_lattice_index",
    "kagome_lattice_tight_binding",
    "kagome_lattice_tight_binding_sparse",
    "kitaev_chain_bdg",
    "longitudinal_field_ising",
    "next_nearest_neighbor_ising",
    "rice_mele_model",
    "square_lattice_index",
    "square_lattice_tight_binding",
    "square_lattice_tight_binding_sparse",
    "ssh_edge_state_localization",
    "ssh_edge_state_localizations",
    "ssh_model",
    "tight_binding_chain",
    "tight_binding_chain_sparse",
    "transverse_field_ising",
    "triangular_lattice_tight_binding",
    "triangular_lattice_tight_binding_sparse",
    "xxz_chain",
    "xy_chain",
]
